### ISSUE TITLE
Chunk fault after directly closing game ( with Disable Custom Worlds Advice mod)

### ISSUE THREAD

**Issue by Rad586** [AstraUnknownDev/unfixed-seeds#1]
**Game version:** 1.18.2 with fabric loader 0.14.19
**Mod version:** 1.0
**Environment:** 
_This combination seems odd, but it's necessary to trigger the bug. Fabric api is not needed._ 
1. DisableCustomWorldsAdvice-2.0
2. unfixed-seeds-1.0

**Description:** 
Directly closing the game causes fault. The screenshot below explains: 
![2023-05-22_19 35 32](https://github.com/ApolloDatapacks/unfixed-seeds/assets/99306685/c51a3df6-9f9d-44c5-bf5b-b826269316cc)
**How to reproduce:** 
1. Create a world and tp to somewhere remote. ( e.g. `/tp @p 123456 200 123456`, This step is for convenience so you won't have to fly that far to see the fault)
2. Press "X" to directly exist Minecraft whilst landing. 
4. Launch Minecraft, rejoin the world, fly straightly for several chunks and you will see the fault.

**Comment by Apollounknowndev** [comment]
I cannot replicate this issue under the exact same circumstances.

**Comment by Rad586** [comment]
> I cannot replicate this issue under the exact same circumstances.

https://github.com/ApolloDatapacks/unfixed-seeds/assets/99306685/45eff6b4-5ab2-4b57-a111-dd795added7f
Here's an edited video for showing this.
Save: 
[New World_.zip](https://github.com/ApolloDatapacks/unfixed-seeds/files/11550426/New.World_.zip)
Logs:
First launch ( creating world then tp): 
[1.log](https://github.com/ApolloDatapacks/unfixed-seeds/files/11550433/1.log)
Second launch: 
[2.log](https://github.com/ApolloDatapacks/unfixed-seeds/files/11550434/2.log)

**Comment by Apollounknowndev** [comment]
Tested it again and was able to replicate it, confirmed.

**Comment by Apollounknowndev** [comment]
Fixed in 1.0.1.
