### ISSUE TITLE
Issue#1 reappeared in terralith 2.2.4

### ISSUE THREAD

**Issue by Rad586** [AstraUnknownDev/unfixed-seeds#2]
**Game version:** 1.18.2 with fabric loader 0.14.19
**Mod version:** 1.0.1
**Environment:**
unfixed-seeds-1.0.1
Terralith_1.18.2_v2.2.4
DisableCustomWorldsAdvice-2.0
cristellib-fabric-1.0.0
fabric-api-0.67.1+1.18.2
**Description:**
#1 
**How to reproduce:**
(same as #1 )
Create a world and tp to somewhere remote. ( e.g. /tp @p 123456 200 123456, This step is for convenience so you won't have to fly that far to see the fault)
Press "X" to directly exist Minecraft whilst landing.
Launch Minecraft, rejoin the world, fly straightly for several chunks and you will see the fault.

**Comment by HaXrDEV** [comment]
Can confirm, happens on my end as well.

**Comment by Apollounknowndev** [comment]
Resolved in 1.0.2.
